archive/urls.py
from django.urls import path

from . import views
# from cmnsdjango import views as cmnsviews
#from core.views import SignUpView

app_name = 'archive'
urlpatterns = [
  # Images
  path('', views.ImageListView.as_view(), name='home'),
  path('object/<int:pk>/', views.ImageRedirectView.as_view(), name='image-redirect'),
  # path('object/<int:pk>/comment/', views.AddCommentView.as_view(), name='comment'),
  path('object/<int:pk>/edit/', views.EditImageView.as_view(), name='image-edit'),
  path('object/new/', views.AddImageView.as_view(), name='add-image'),
  path('object/<str:slug>/', views.ImageView.as_view(), name='image'),
  # path('object/<str:slug>/love/', views.ToggleFavoriteImage.as_view(), name='love-image'),
  path('object/<int:pk>:<str:slug>/regeneratethumbnail/', views.RegenerateThumbnailView.as_view(), name='regenerate-thumbnail'),
  # Special Image views
  path('objects/<int:decade>/', views.ImageListView.as_view(), {'columns': ('decade')}, name='images-by-decade'),
  path('objects/by:<str:user>/', views.ImageListView.as_view(), {'columns': ('user')}, name='image-by-uploader'),
  path('objects/<str:tag>/', views.ImageListView.as_view(), {'columns': ('tag')}, name='image-with-tag'),
  path('objects/a/comments/', views.aListComments.as_view(), name='acomments'),
  path('objects/', views.ImageListView.as_view(), name='images'),

  # People
  path('people/', views.PersonListView.as_view(), name='people'),
  path('person/<int:pk>/', views.PersonRedirectView.as_view(), name='person-short'),
  path('person/<int:pk>/edit/', views.EditPersonView.as_view(), name='person-edit'),
  path('person/<int:pk>/<name>/', views.PersonView.as_view(), name='person'),
  path('person/new/', views.AddPersonView.as_view(), name='add-person'),
  path('person/add/', views.AddPerson.as_view(), name='new-add-person'),
  # Portrait
  # path('person/<int:subject>/portrait:<int:removed_image>/delete/', views.RemovePortraitView.as_view(), name='remove-portrait'),
  # Relationships
  path('person/<int:subject>/<str:type>:<int:removed_person>/delete/', views.PersonRemoveRelationView.as_view(), {'columns': ('up', 'relation', 'down')}, name='remove-relationship'),
  path('person/add-relation/', views.PersonAddRelationView.as_view(), name='add-relationship'),
  path('person/<int:pk>/<str:slug>/suggest-family/', views.SuggestFamilyView.as_view(), name='suggest-family'),
  # Tree
  path('tree/<int:pk>/', views.TreeView.as_view(), name="tree"),
  # Add Image
  path('person/<int:subject_id>:<str:subject_slug>/add-image/', views.AddImageView.as_view(), name='add-person-image'),
  
  # Tags 
  path('tags/', views.TagListView.as_view(), name='tags'),
  path('tag/new/', views.AddTagView.as_view(), name='add-tag'),
  path('tag/<str:slug>/', views.EditTagView.as_view(), name='edit-tag'),

  # Notes
  path('notes/', views.NotesListView.as_view(), name='notes'),
  path('note/<int:pk>/edit/', views.EditNoteView.as_view(), name='note-edit'),
  path('note/<int:pk>/', views.NoteView.as_view(), name='note'),
  path('note/<int:pk>/<title>/', views.NoteView.as_view(), name='note-with-name'),
  path('note/new/', views.AddNoteView.as_view(), name='add-note'),

  # Comments
  path('comments/', views.CommentListView.as_view(), name='comments'),
  
  # Attachments
  path('attachments/', views.AttachmentListView.as_view(), name='attachments'),
  path('attachment/new/', views.AttachmentAddView.as_view(), name='add-attachment'),
  path('attachments/<str:user>/', views.AttachmentListView.as_view(), name='user-attachments'),
  path('attachment/<str:slug>/delete/', views.AttachmentDeleteView.as_view(), name='delete-attachment'),
  path('attachment/<str:slug>/edit/', views.AttachmentEditView.as_view(), name='edit-attachment'),
  path('attachment/<str:slug>/create-image/', views.CreateImageFromAttachmentView.as_view(), name='create-image-from-attachment'),
  path('attachment/<str:slug>/', views.AttachmentStreamView.as_view(), name='attachment'),
  
  # Locations
  path('locations/', views.LocationListView.as_view(), name='locations'),
  
  # Accounts
  path('settings/', views.PreferencesView.as_view(), name='settings'),
  path("sign-up/", views.SignUpView.as_view(), name='signup'),

  # # JSON
  # # JSON GET Attributes
  # path('json/<str:model>/<int:pk>:<str:slug>/attribute/<str:field>/', cmnsviews.JsonGetAttributes.as_view(), name='json-get-attributes-by-pk-slug'),
  # path('json/<str:model>/<str:slug>/attribute/<str:field>/', cmnsviews.JsonGetAttributes.as_view(), name='json-get-attributes'),
  # path('json/<str:model>/attribute/<str:field>/', cmnsviews.JsonGetAttributes.as_view(), name='json-get-attributes-for-self'),
  # # JSON GET Suggestions
  # path('json/<str:model>/<int:pk>:<str:slug>/suggest/<str:field>/', cmnsviews.JsonGetSuggestions.as_view(), name='json-get-suggestions-by-pk-slug'),
  # path('json/<str:model>/<str:slug>/suggest/<str:field>/', cmnsviews.JsonGetSuggestions.as_view(), name='json-get-suggestions'),
  # path('json/<str:model>/suggest/<str:field>/', cmnsviews.JsonGetSuggestions.as_view(), name='json-get-suggestions-for-self'),
  # # JSON SET Attributes
  # path('json/<str:model>/<int:pk>:<str:slug>/set/<str:field>/', cmnsviews.JsonSetAttribute.as_view(), name='json-set-attribute-by-pk-slug'),
  # path('json/<str:model>/<str:slug>/set/<str:field>/', cmnsviews.JsonSetAttribute.as_view(), name='json-set-attribute'),
  # path('json/<str:model>/set/<str:field>/', cmnsviews.JsonSetAttribute.as_view(), name='json-set-attribute-for-self'),
  # # JSON getAttribute Form
  # path('json/<str:model>/<str:slug>/add/<str:field>/', cmnsviews.GetJsonAddObjectForm.as_view(), name='json-suggestion-form'),
  # # path('json/person:<int:pk>:<str:slug>/attribute/<str:attribute>/', views.JsonGetAttributeOfPerson.as_view(), name='json-get-attribute-of-person'),
  # path('json/object:<int:pk>:<str:slug>/comments/', views.aListComments.as_view(), name='acommentsforimage'),
  # path('json/object:<int:pk>:<str:slug>/commentform/', views.aFetchCommentForm.as_view(), name='fetchcommentform'),
  # path('json/object:<int:pk>:<str:slug>/postcomment/', views.aPostComment.as_view(), name='postcomment'),
  
]

family/urls.py
"""family URL Configuration"""

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  # path('pick/', include('datepicker.urls')),
  path('', include('archive.urls')),
  path('ajax/', include('cmnsd.urls')),
  path('admin/', admin.site.urls),
  path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archive/models/image.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from PIL import Image as PIL
from pathlib import Path
from django.core.validators import MaxValueValidator, MinValueValidator
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _

from math import floor

from .tag import Tag
from .person import Person
from .Category import Category

from cmnsd.models.cmnsd_basemodel import BaseModel, VisibilityModel
from cmnsd.models.cmnsd_basemethod import ajax_function, searchable_function
from cmnsd.views.cmnsd_filter import FilterMixin
from cmnsd.views.utils__request import RequestMixin

# Create Thumbnail function
def get_thumbnail(image):
  # Check if suffix is supported.
  if image.name[-4:].lower() not in ['.jpg', '.png'] and \
     image.name[-5:].lower() not in ['.jpeg',]:
    # There is an image ready that reads Format Not Supported. This is a
    # friendly way to inform the user of the error.
    return 'documents/format_not_supported.jpg'
  #from PIL import Image
  import PIL
  PIL.Image.MAX_IMAGE_PIXELS = 933120000
  ''' Store Target Information '''
  tgt_width = 300
  tgt_path = settings.MEDIA_ROOT.joinpath('thumbnails/')
  tgt_file = str(image.name)
  ''' Check if thumbnails_dir exists '''
  if not tgt_path.exists():
    tgt_path.mkdir(parents=True, exist_ok=True)
  ''' Set destination '''
  try:
    with PIL.Image.open(image.path) as img:
      width, height = img.size
      ratio = width / height
      tgt_height = int(tgt_width / ratio)
      img = img.resize((tgt_width, tgt_height), PIL.Image.Resampling.LANCZOS)
      img.save(settings.MEDIA_ROOT.joinpath(tgt_file))
      return tgt_file
  except Exception as e:
    return None

class Group(BaseModel):
  title               = models.CharField(max_length=255, blank=True)
  description         = models.CharField(max_length=512, blank=True, null=True)
  user                = models.ForeignKey(User, on_delete=models.CASCADE)
  tag                 = models.ManyToManyField(Tag, blank=True, related_name='groups')
  
  def __str__(self):
    title = self.title
    ''' Prepend title with tag if there is one tag set. 
        If more tags are set, it would get too messy. 
    '''
    if self.tag and self.tag.all().count() == 1:
      for tag in self.tag.all():
        title = f"{ tag }: { title }"
    ''' Append title with short description if set 
    '''
    if self.description:
      title += ' (' + self.description[:32]
      if len(self.description) > 32:
        title += '...'
      self.title += ')'
    return title

  def count_images(self):
    return self.images.exclude(status='x').count()

class Attachment(BaseModel):
  slug                = models.CharField(max_length=255, unique=True)
  file                = models.FileField(null=True, upload_to='files', help_text='Possible to attach file to an image. Use for pdf, doc, excel, etc.')
  description         = models.CharField(max_length=512, blank=True, null=True)
  # Meta
  size                = models.IntegerField(default=0)
  is_deleted          = models.BooleanField(default=False)

  def __str__(self) -> str:
    description = str(self.description)
    if len(description) < 1:
      description = self.slug
    # if self.is_deleted:
    #   description = f"[Deleted] { description }"
    return str(description)
    
  def get_absolute_url(self):
      return reverse("archive:attachment", kwargs={"slug": self.slug})
  
  def filename(self):
    return Path(str(self.file)).name
  
  def extension(self):
    return Path(str(self.file)).suffix[1:].lower()

  def storeSize(self):
    from os import stat
    file_stats = stat(settings.MEDIA_ROOT.joinpath(str(self.file  )))
    self.size = file_stats.st_size
    self.save()

  ''' Display Image File size. Calculate if not stored yet '''
  def getSize(self):
    ''' https://stackoverflow.com/questions/5194057/better-way-to-convert-file-sizes-in-python '''
    from math import floor, pow, log
    if self.size == 0:
      self.storeSize()
    if self.size == 0:
      return "0B"
    size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
    i = int(floor(log(self.size, 1024)))
    p = pow(1024, i)
    s = round(self.size / p, 2)
    return "%s %s" % (s, size_name[i])

''' Use default random value when migrating to slug '''
import random
def random_string():
  return str(random.randint(10000, 99999))

class Image(BaseModel, RequestMixin, FilterMixin):
  # Document details
  slug                = models.CharField(max_length=255, unique=True, default=random_string)
  source              = models.FileField()
  thumbnail           = models.CharField(max_length=2000, blank=True, null=True)
  title               = models.CharField(max_length=255)
  description         = models.TextField(blank=True, help_text='Markdown supported')
  document_source     = models.CharField(max_length=255, blank=True, help_text='Link or textual description of source')
  # Relations
  category            = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, related_name='images')
  people              = models.ManyToManyField(Person, blank=True, related_name='images', help_text='Tag people that are on the photo')
  tag                 = models.ManyToManyField(Tag, blank=True, related_name='images')
  attachments         = models.ManyToManyField(Attachment, blank=True, related_name='images')
  is_portrait_of      = models.OneToOneField(Person, on_delete=models.CASCADE, related_name='portrait', blank=True, null=True)
  portrait_of         = models.ManyToManyField(Person, blank=True, related_name='portraits', help_text='Tag people for whom this image is a portrait')
  in_group            = models.ManyToManyField(Group, blank=True, related_name='images', help_text='Group images')
  family              = models.CharField(max_length=64, null=True, blank=True, help_text=_('Add image to family collection if no family member can be tagged'))
  # Dating
  MONTHS = [(1, _('january')), (2, _('february')), (3, _('march')), (4, _('april')), (5, _('may')), (6, _('june')), (7, _('july')), (8, _('august')), (9, _('september')), (10, _('october')), (11, _('november')), (12, _('december'))]
  year                = models.PositiveSmallIntegerField(blank=True, null=True, help_text='')
  month               = models.PositiveSmallIntegerField(blank=True, null=True, help_text='', choices=MONTHS)
  day                 = models.PositiveSmallIntegerField(blank=True, null=True, help_text='', validators=[MaxValueValidator(31), MinValueValidator(1)])
  # Meta
  size                = models.IntegerField(default=0)
  width               = models.IntegerField(default=0)
  height              = models.IntegerField(default=0)
  
  visibility_frontpage     = models.BooleanField(default=True)
  visibility_person_page   = models.BooleanField(default=True)
  
  def date(self):
    """ Returns the date of the image by combining the year, month and day fields """
    return f"{self.day} {self.MONTHS[self.month-1][1]} {self.year}"
  
  def __str__(self):
    return self.get_indexed_name()

  ''' Shorthand Ajax Functions to access multiple fields '''
  @ajax_function
  def origin(self):
    return {
      'document_source': str(self.document_source),
      'date': f"{ self.day if self.day else '*'}-{self.month if self.month else '*'}-{self.year if self.year else '*'}",
      'day': self.day,
      'month': self.month,
      'year': self.year,
      'months': self.MONTHS,
    }
  @ajax_function
  def metadata(self):
    return {
      'attachments': self.get_attachments(),
      'size': self.getSize(),
      'dimensions': {
        'width': self.width,
        'height': self.height,
      },
      'extension': self.extension(),
      'user': self.user,
      'users': User.objects.all(),
      'date_shared': self.date_created,
    }
  @ajax_function
  def classification(self):
    return {
      'tag': self.tag.all(),
      'groups': self.in_group.all(),
      'grouped_items': self.grouped_items(),
      'family': self.family,
      'family_collection': self.family_collection(),
      'automated_family': self.automated_family(),
      'available_families': self.families(),
    }
  
  @ajax_function
  def actionlist(self):
    return True
  
  @searchable_function
  def familycollection(self):
    return self.family_collection()
  
  @searchable_function
  def decade(self):
    if self.year:
      decade = floor(self.year / 10) * 10
      return decade
    return None
  
  ''' Get Save Slug
      Loop through existing slugs and append slug with counter if Unique contraint would fail
  '''
  def get_safe_slug(self, title, is_deleted):
    slug = slugify(title).lower()
    if is_deleted:
      slug = f"[deleted]_{slug}"
    images = Image.objects.all().values_list('slug')
    if images.filter(slug=slug).count() > 0:
      i = 1
      while images.filter(slug=f"{slug}{str(i)}").count() > 0:
        i += 1
      slug = f"{slug}{str(i)}"
    return slug

  def get_indexed_name(self):
    title = self.title if self.title != '' else '--no title--'
    id = str(self.id)
    while len(id) < 4:
      id = '0' + id
    if self.status == 'x':
      title += ' (deleted)'
    return id + ' ' + title
  
  ''' Related Object Methods'''
  def count_comments(self):
    return self.get_comments().count()
  def get_comments(self):
    return self.filter(self.comments)
  def count_attachments(self):
    return self.get_attachments().count()
  def get_attachments(self):
    return self.filter(self.attachments)
  
  def get_groups(self):
    groups = {}
    for group in self.in_group.all():
      if group.images.exclude(status='x').count() > 1:
        groups[group.title] = group.images.exclude(status='x').count()
    return groups
  def get_grouped_images(self):
    groups = {}
    for group in self.in_group.all():

archive/forms.py
from django import forms
from django.forms import ClearableFileInput
#from django.contrib.auth.models import User
#from django.contrib.auth.forms import UserCreationForm

#from .models import Document

# Multiple File Upload
class ImagesUploadForm(forms.Form):
    # Keep name to 'file' because that's what Dropzone is using
    source = forms.ImageField(required=True)
#class ImagesUploadForm(forms.Form):
#  file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

archive/views/Locations.py
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import redirect
from django.conf import settings
from django.contrib import messages
from django.urls import reverse
from django.utils.translation import gettext as _

from django.contrib.auth.mixins import PermissionRequiredMixin

from archive.models import Location

from cmnsd.views.cmnsd_filter import FilterMixin

class LocationListView(FilterMixin, ListView):
  model = Location

  def get_queryset(self):
    queryset = super().get_queryset()
    queryset = self.filter(queryset)
    return queryset.order_by('parent__parent__name', 'parent__name', 'name')

archive/templates/objects/comment.html
{% load i18n %}{% load static %}<li class="bi bi-chat-right-text">
  <div class="comment">
    {% if show_thumbnail %}
      <div class="thumbnail">
        <a href="{% url 'archive:image' comment.image.slug %}"><img src="/documents/{{ comment.image.thumbnail }}" alt="{{ comment.image.title }}" title="{{ comment.image.title }} - {{ comment.image.description }}"></a>
      </div>
    {% endif %}
    <div class="content">
      <h4>{% if comment.user.first_name %}{{ comment.user.first_name }} {{ comment.user.last_name }}{% else %}{{ comment.user }}{% endif %} {% translate 'wrote on' %} {{ comment.date_created|date:'d/m/Y' }}{% if show_thumbnail %} {% translate 'on'%} <a href="{% url 'archive:image' comment.image.slug %}">{{ comment.image.title|title }}{% endif %}</a>:</h4>
      {{ comment.content|markdown|safe }}
      {% if comment.user == user or user.is_staff %}
        <span class="actions">
          {% if comment.user == user %}<a href="{% url 'archive:edit-comment' comment.id %}">{% translate 'edit'|capfirst %} {% translate 'comment' %}</a>{% endif %}
          {% if user.is_staff %}<a href="/admin/archive/comment/{{ comment.id }}/change/">{% translate 'edit'|capfirst %} {% translate 'in admin' %}</a>{% endif %}
          {% if comment.user == user or user.is_staff %}<a href="{% url 'archive:delete-comment' comment.id %}">{% translate 'delete'|capfirst %} {% translate 'comment' %}</a>{% endif %}
        </span>
      {% endif %}
    </div>
  </div>
</li>

archive/templates/objects/image_description.html
{% load i18n %}{% load static %}<div class="description attribute">{{ description|markdown|safe }}
{% if perms.archive.change_image and not disallow_delete_attribute %}<span class="clickable " 
        data-url="{% url 'archive:json-suggestion-form' 'image' image.slug 'description' %}" 
        data-action="getOverlay"
        title="{% translate 'edit description'|capfirst %}" data-bs-toggle="tooltip" data-bs-placement="top">
        <svg class="bi" width="16" height="16" fill="currentColor"><use xlink:href="{% static 'bootstrap-icons/bootstrap-icons.svg' %}#pencil"/></svg>
  </span>{% endif %}
</li>
</div>

archive/templates/objects/person.html
{% load i18n %}<li class="bi bi-person-fill attribute"><span class="name">
  {% if not person.private %}<a href="{% url 'archive:person' person.id person.slug|default:'details' %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Bekijk details van {{ person.full_name }}">{% endif %}{{ person.full_name }}{% if not person.private %}</a>{% endif %}</span>
<span class="date">{% if person.year_of_birth %}{{ person.year_of_birth }}{% elif person.year_of_death %}&nbsp;&nbsp;&nbsp;&nbsp;{% endif %}{% if person.year_of_death or person.moment_of_death_unconfirmed %} - {% if person.year_of_death %}{{ person.year_of_death }}{% else %}?{% endif %}{% endif %}</span>
{% if not suppress_icons %}
  <span class="icons">
    <!-- bio -->{% if person.bio %}<i class="bi bi-journal-text" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ person.name }} heeft een biografie"></i>{% endif %}
    <!-- images -->{% if person.images.all.count > 0 %} <i class="bi bi-image{% if person.images.all.count > 1 %}s{% endif %}" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ person.images.all.count }} afbeeldingen met {{ person.name }}"></i>{{ person.images.all.count }}{% endif %}
    <!-- notes -->{% if person.notes.all.count > 0 %} <i class="bi-stick{% if person.notes.all.count > 1 %}ies{% else %}y{% endif %}" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ person.notes.all.count }} notities met {{ person.name }}"></i>{{ person.notes.all.count }}{% endif %}
    <!-- comments -->{% if person.related_user.comments.all.count > 0 %} <a href="{% url 'archive:comments' %}?user={{ person.related_user.username }}" class="bi bi-chat" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ person.related_user.comments.all.count }} reacties door {{ person.name }}">{{ person.related_user.comments.all.count }}</a>{% endif %}
  </span>
{% endif %}
{% comment %} {% if perms.archive.change_image and not disallow_delete_attribute %}<span class="clickable"
        data-slug="{{ person.slug }}"
        data-url="{% url 'archive:json-set-attribute-by-pk-slug' 'image' image.id image.slug 'people' %}?obj_id={{ person.id }}" 
        data-success-url="{% url 'archive:json-get-attributes-by-pk-slug' 'image' image.id image.slug 'people' %}"
        data-attribute="people"
        data-action="setAttribute"
        title="{% translate 'remove'|capfirst %} '{{ person.name|title }}'" data-bs-toggle="tooltip" data-bs-placement="top">
      <i class="bi bi-x"></i>
  </span>{% endif %} {% endcomment %}
</li>

archive/templates/objects/preference_show_new_uploads.html
{{ show_new_uploads|safe }}

archive/templates/objects/tag.html
{% load i18n %}<li class="tag bi bi-tag-fill attribute">
  <a href="{% url 'archive:image-with-tag' tag.slug %}" class="tag" title="{{ tag.images.all.count }} afbeeldingen met tag '{{ tag.title|title }}'" data-bs-toggle="tooltip" data-bs-placement="top">{% if compact %}{{ tag.title|title|truncatechars:12 }}{% else %}{{ tag.title|title }}{% endif %}</a> {% if tag.images.all.count > 0 %}({{ tag.images.all.count }}){% endif %}
  {% comment %} {% if perms.archive.change_image and not disallow_delete_attribute %}<span class="clickable"
        data-slug="{{ tag.slug }}"
        data-url="{% url 'archive:json-set-attribute-by-pk-slug' 'image' image.id image.slug 'tag' %}?obj_id={{ tag.id }}" 
        data-success-url="{% url 'archive:json-get-attributes-by-pk-slug' 'image' image.id image.slug 'tag' %}"
        data-action="setAttribute"
        data-attribute="tag"
        title="{% translate 'remove tag'|capfirst %} {{ field_name }} '{{ tag.title|title }}' from &quot;{{ image.title }}&quot;" data-bs-toggle="tooltip" data-bs-placement="top">
      <i class="bi bi-x"></i>
  </span>{% endif %} {% endcomment %}
</li>

archive/templates/objects/user.html
{{ user.get_full_name|default:user.username }}