archive/urls.py
from django.urls import path

from . import views
# from cmnsdjango import views as cmnsviews
#from core.views import SignUpView

app_name = 'archive'
urlpatterns = [
  # Images
  path('', views.ImageListView.as_view(), name='home'),
  path('object/<int:pk>/', views.ImageRedirectView.as_view(), name='image-redirect'),
  # path('object/<int:pk>/comment/', views.AddCommentView.as_view(), name='comment'),
  path('object/<int:pk>/edit/', views.EditImageView.as_view(), name='image-edit'),
  path('object/new/', views.AddImageView.as_view(), name='add-image'),
  path('object/<str:slug>/', views.ImageView.as_view(), name='image'),
  # path('object/<str:slug>/love/', views.ToggleFavoriteImage.as_view(), name='love-image'),
  path('object/<int:pk>:<str:slug>/regeneratethumbnail/', views.RegenerateThumbnailView.as_view(), name='regenerate-thumbnail'),
  # Special Image views
  path('objects/<int:decade>/', views.ImageListView.as_view(), {'columns': ('decade')}, name='images-by-decade'),
  path('objects/by:<str:user>/', views.ImageListView.as_view(), {'columns': ('user')}, name='image-by-uploader'),
  path('objects/<str:tag>/', views.ImageListView.as_view(), {'columns': ('tag')}, name='image-with-tag'),
  path('objects/a/comments/', views.aListComments.as_view(), name='acomments'),
  path('objects/', views.ImageListView.as_view(), name='images'),

  # People
  path('people/', views.PersonListView.as_view(), name='people'),
  path('person/<int:pk>/', views.PersonRedirectView.as_view(), name='person-short'),
  path('person/<int:pk>/edit/', views.EditPersonView.as_view(), name='person-edit'),
  path('person/<int:pk>/<name>/', views.PersonView.as_view(), name='person'),
  path('person/new/', views.AddPersonView.as_view(), name='add-person'),
  path('person/add/', views.AddPerson.as_view(), name='new-add-person'),
  # Portrait
  # path('person/<int:subject>/portrait:<int:removed_image>/delete/', views.RemovePortraitView.as_view(), name='remove-portrait'),
  # Relationships
  path('person/<int:subject>/<str:type>:<int:removed_person>/delete/', views.PersonRemoveRelationView.as_view(), {'columns': ('up', 'relation', 'down')}, name='remove-relationship'),
  path('person/add-relation/', views.PersonAddRelationView.as_view(), name='add-relationship'),
  path('person/<int:pk>/<str:slug>/suggest-family/', views.SuggestFamilyView.as_view(), name='suggest-family'),
  # Tree
  path('tree/<int:pk>/', views.TreeView.as_view(), name="tree"),
  # Add Image
  path('person/<int:subject_id>:<str:subject_slug>/add-image/', views.AddImageView.as_view(), name='add-person-image'),
  
  # Tags 
  path('tags/', views.TagListView.as_view(), name='tags'),
  path('tag/new/', views.AddTagView.as_view(), name='add-tag'),
  path('tag/<str:slug>/', views.EditTagView.as_view(), name='edit-tag'),

  # Notes
  path('notes/', views.NotesListView.as_view(), name='notes'),
  path('note/<int:pk>/edit/', views.EditNoteView.as_view(), name='note-edit'),
  path('note/<int:pk>/', views.NoteView.as_view(), name='note'),
  path('note/<int:pk>/<title>/', views.NoteView.as_view(), name='note-with-name'),
  path('note/new/', views.AddNoteView.as_view(), name='add-note'),

  # Comments
  path('comments/', views.CommentListView.as_view(), name='comments'),
  
  # Attachments
  path('attachments/', views.AttachmentListView.as_view(), name='attachments'),
  path('attachment/new/', views.AttachmentAddView.as_view(), name='add-attachment'),
  path('attachments/<str:user>/', views.AttachmentListView.as_view(), name='user-attachments'),
  path('attachment/<str:slug>/delete/', views.AttachmentDeleteView.as_view(), name='delete-attachment'),
  path('attachment/<str:slug>/edit/', views.AttachmentEditView.as_view(), name='edit-attachment'),
  path('attachment/<str:slug>/create-image/', views.CreateImageFromAttachmentView.as_view(), name='create-image-from-attachment'),
  path('attachment/<str:slug>/', views.AttachmentStreamView.as_view(), name='attachment'),
  
  # Locations
  path('locations/', views.LocationListView.as_view(), name='locations'),
  
  # Accounts
  path('settings/', views.PreferencesView.as_view(), name='settings'),
  path("sign-up/", views.SignUpView.as_view(), name='signup'),

  # # JSON
  # # JSON GET Attributes
  # path('json/<str:model>/<int:pk>:<str:slug>/attribute/<str:field>/', cmnsviews.JsonGetAttributes.as_view(), name='json-get-attributes-by-pk-slug'),
  # path('json/<str:model>/<str:slug>/attribute/<str:field>/', cmnsviews.JsonGetAttributes.as_view(), name='json-get-attributes'),
  # path('json/<str:model>/attribute/<str:field>/', cmnsviews.JsonGetAttributes.as_view(), name='json-get-attributes-for-self'),
  # # JSON GET Suggestions
  # path('json/<str:model>/<int:pk>:<str:slug>/suggest/<str:field>/', cmnsviews.JsonGetSuggestions.as_view(), name='json-get-suggestions-by-pk-slug'),
  # path('json/<str:model>/<str:slug>/suggest/<str:field>/', cmnsviews.JsonGetSuggestions.as_view(), name='json-get-suggestions'),
  # path('json/<str:model>/suggest/<str:field>/', cmnsviews.JsonGetSuggestions.as_view(), name='json-get-suggestions-for-self'),
  # # JSON SET Attributes
  # path('json/<str:model>/<int:pk>:<str:slug>/set/<str:field>/', cmnsviews.JsonSetAttribute.as_view(), name='json-set-attribute-by-pk-slug'),
  # path('json/<str:model>/<str:slug>/set/<str:field>/', cmnsviews.JsonSetAttribute.as_view(), name='json-set-attribute'),
  # path('json/<str:model>/set/<str:field>/', cmnsviews.JsonSetAttribute.as_view(), name='json-set-attribute-for-self'),
  # # JSON getAttribute Form
  # path('json/<str:model>/<str:slug>/add/<str:field>/', cmnsviews.GetJsonAddObjectForm.as_view(), name='json-suggestion-form'),
  # # path('json/person:<int:pk>:<str:slug>/attribute/<str:attribute>/', views.JsonGetAttributeOfPerson.as_view(), name='json-get-attribute-of-person'),
  # path('json/object:<int:pk>:<str:slug>/comments/', views.aListComments.as_view(), name='acommentsforimage'),
  # path('json/object:<int:pk>:<str:slug>/commentform/', views.aFetchCommentForm.as_view(), name='fetchcommentform'),
  # path('json/object:<int:pk>:<str:slug>/postcomment/', views.aPostComment.as_view(), name='postcomment'),
  
]

family/urls.py
"""family URL Configuration"""

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  # path('pick/', include('datepicker.urls')),
  path('', include('archive.urls')),
  path('ajax/', include('cmnsd.urls')),
  path('admin/', admin.site.urls),
  path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archive/models/BaseIcon.py
from django.db import models

class BaseIcon(models.Model):
  icon = models.CharField(max_length=255, blank=True, help_text='bootstrap icon name')

  class Meta:
    abstract = True

  def get_icon_file(self):
    if self.icon:
      return f'img/bootstrap-icons/{self.icon}.svg'
    return 'img/bootstrap-icons/list.svg'

archive/models/Location.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.template.defaultfilters import slugify
from cmnsd.models.cmnsd_basemodel import BaseModel
from .BaseIcon import BaseIcon

class Location(BaseModel, BaseIcon):
  slug                = models.SlugField(max_length=255, unique=True)
  name                = models.CharField(max_length=255)
  description         = models.TextField(blank=True)
  parent              = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='sublocations')
  alternatives        = models.ManyToManyField('self', blank=True, symmetrical=False, related_name='alternative_to')

  coord_lat           = models.FloatField(null=True, blank=True, validators=[MinValueValidator(-90.0), MaxValueValidator(90.0)])
  coord_lon           = models.FloatField(null=True, blank=True, validators=[MinValueValidator(-180.0), MaxValueValidator(180.0)])

  def __str__(self):
    return self.get_display_name()
  
  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = slugify(self.name)
    super().save(*args, **kwargs)
  
  class Meta:
    ordering = ['parent__parent__name', 'parent__name', 'name']
    unique_together = ('parent', 'name')
  
  def get_display_name(self):
    name = self.name
    if self.parent:
      name += f", { self.parent.name }"
    if self.parent and self.parent.parent:
      name += f", { self.parent.parent.name }"
    return name
  
  def get_alternatives(self):
    alternatives = self.alternatives.all() | self.alternative_to.all()
    return alternatives.distinct()
  
  def get_event_people(self):
    people = set()
    for event in self.events.all():
      for person in event.people.all():
        people.add(person)
    return people
  def people(self):
    return self.get_event_people()
  
  def country(self):
    if self.parent and self.parent.parent:
      return self.parent.parent
    elif self.parent:
      return self.parent
    else:
      return None
  def region(self):
    if self.parent and self.parent.parent:
      return self.parent
    else:
      return None

archive/models/comment.py
from django.db import models
from .image import Image
from django.urls import reverse

from cmnsd.models.cmnsd_basemodel import BaseModel
  
class Comment(BaseModel):
  # Content
  content             = models.TextField(help_text='Markdown supported')
  image               = models.ForeignKey(Image, related_name='comments', on_delete=models.CASCADE)
  
  class Meta:
    ''' Unique together
        Any comment to an image should be unique for that image and user,
        disallowing double comments.
    '''
    unique_together = ('user', 'image', 'content')
    ordering = ['-date_created']

  def __str__(self):
    deleted = ' (deleted)' if self.status == 'x' else ''
    return self.user.username + ' on ' + self.image.title + deleted
  
  def get_absolute_url(self):
    return reverse('archive:image', kwargs={'slug': self.image.slug})

archive/views/Locations.py
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.shortcuts import redirect
from django.conf import settings
from django.contrib import messages
from django.urls import reverse
from django.utils.translation import gettext as _

from django.contrib.auth.mixins import PermissionRequiredMixin

from archive.models import Location

from cmnsd.views.cmnsd_filter import FilterMixin

class LocationListView(FilterMixin, ListView):
  model = Location

  def get_queryset(self):
    queryset = super().get_queryset()
    queryset = self.filter(queryset)
    return queryset.order_by('parent__parent__name', 'parent__name', 'name')

archive/views/aComment.py
from django.views.generic import DetailView, ListView, TemplateView
from django.template.loader import render_to_string
from django.shortcuts import redirect
from django.contrib import messages
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.db.utils import IntegrityError
from django.conf import settings

from archive.models import Image
from archive.models.comment import Comment

''' List comments by date added newest first 
    This view returns a list of comments sorted by date added.
    When a specific image is mentioned in the URL, only comments for that image are returned.
    When a specific user is mentioned in the URL, only comments by that user are returned.
    When no filters are mentioned, all comments are returned.
    @Todo: Add pagination
'''
class aListComments(ListView):
  model = Comment

  def get(self, request, *args, **kwargs):
    response = {
      'error': False,
      'message': '',
      'object': {},
      'payload': [],
    }
    ''' Show thumbnail in comments should be se to
        False when comments are rendered for a specific object
        else True
    '''
    show_thumbnail = True
    ''' Validate that user is logged in '''
    if not self.request.user.is_authenticated:
      response['error'] = True
      response['message'] = _('you need to be logged in to view comments').capitalize()
      return JsonResponse(response)
    ''' Validate object if object is mentioned in URL '''
    object = self.getObject()
    if object == False:
      ''' Object is mentioned in URL but not found '''
      return JsonResponse({
        'error': True,
        'message': _('object not found').capitalize(),
      })
    elif object:
      ''' Add object details to response '''
      response['object'] = {
        'id': object.id,
        'title': object.title,
        'slug': object.slug,
        'url': object.get_absolute_url(),
        'comment_count': object.count_comments(),
      }
      show_thumbnail = False
    ''' Render comments 
        Add all rendered comments to payload
    '''
    comments = self.getComments(object)
    if comments == False:
      return JsonResponse({
        'error': True,
        'message': _('comments cannot be loaded').capitalize(),
      })
    if object and object.count_comments() > 0:
      response['payload'].append(render_to_string('archive/partial/commentcounter.html', {'image': object, }))
    for comment in comments:
      response['payload'].append(render_to_string('archive/partial/comment.html', {'comment': comment, 'show_thumbnail': show_thumbnail, 'user':self.request.user }))
    ''' Return response '''
    return JsonResponse(response)
  
  ''' Fetch object information
      Returns the object if id and slug are mentioned in URL
      Returns False if object is mentioned in URL but not found
      Returns None if object is not mentioned in URL
  '''
  def getObject(self):
    try:
      object = Image.objects.get(pk=self.kwargs['pk'], slug=self.kwargs['slug'])
    except KeyError:
      object = None
    except Image.DoesNotExist:
      object = False
    return object
  
  ''' Fetch comments
      Returns all not-deleted comments
      Filters comments by object if object is mentioned in URL
      Filters comments by user if user is mentioned in URL query parameter
  '''
  def getComments(self, object):
    ''' Fetch all not deleted comments '''
    comments = Comment.objects.all().exclude(is_deleted=True)
    ''' Process filters: get comments for object 
        If no PK or SLUG in url kwargs, return all comments
    '''
    if 'pk' in self.kwargs and 'slug' in self.kwargs:
      comments = comments.filter(image=self.getObject())
    ''' Process filters: get comments for user '''
    if self.request.GET.get('user', False):
      try:
        user = User.objects.get(username__iexact=self.request.GET.get('user'))
        comments = comments.filter(user=user)
      except User.DoesNotExist:
        return False
    ''' Order comments by date_modified '''
    order = 'date_modified' if self.request.GET.get('o', False) == '-' else '-date_modified'
    ''' Return comments '''
    comments = comments.order_by(order).distinct()
    return comments
  
''' Fetch comment form 
    This view returns a rendered comment form for the image to inject
    into the image detail page via ajax request
'''
class aFetchCommentForm(TemplateView):
  
  def get(self, *args, **kwargs):
    response = {
      'error': False,
      'message': '',
      'payload': render_to_string('archive/partial/commentform.html', {'image': Image.objects.get(pk=self.kwargs['pk'], slug=self.kwargs['slug'])}),
    }
    ''' Validate that user is logged in '''
    return JsonResponse(response)


''' Post comment
    This view allows users to post comments to images via ajax request.
'''
class aPostComment(TemplateView):
  template_name = 'archive/partial/comment.html'

  def get(self, *args, **kwargs):
    messages.add_message(self.request, messages.ERROR, _('You are not allowed to access this page directly.').capitalize())
    if 'slug' in self.kwargs:
      return redirect('archive:image', slug=self.kwargs['slug'])
    return redirect('archive:home')
     
  def post(self, *args, **kwargs):
    response = {
      'error': False,
      'message': '',
      'payload': '',
    }
    ''' Validate that user is logged in '''
    if not self.request.user.is_authenticated:
      response['error'] = True
      response['message'] = _('you need to be logged in to comment').capitalize()
      return JsonResponse(response)
    if not self.request.user.has_perm('archive.add_comment'):
      response['error'] = True
      response['message'] = _('you are not allowed to comment').capitalize()
      return JsonResponse
    ''' Validate object '''
    try:
      object = Image.objects.get(pk=self.kwargs['pk'], slug=self.kwargs['slug'])
    except Image.DoesNotExist:
      response['error'] = True
      response['message'] = _('object not found').capitalize()
      return JsonResponse(response)
    ''' Validate comment - cannot be empty '''
    comment = self.request.POST.get('comment', False)
    if not comment:
      response['error'] = True
      response['message'] = _('comment cannot be empty').capitalize()
      return JsonResponse(response)
    comment = comment.strip()
    ''' Comments should have a minimum length in characters, so exclude space from check '''
    if len(comment.replace(' ', '')) < getattr(settings, 'MIN_COMMENT_LENGTH', 5):
      response['error'] = True
      response['message'] = _('comment is too short').capitalize()
      return JsonResponse(response)
    ''' Create comment '''
    try:
      comment = Comment(
        user=self.request.user,
        image=object,
        content=self.request.POST.get('comment'),
      )
      comment.save()
    except IntegrityError:
      response['error'] = True
      response['message'] = _('you have already posted this comment').capitalize()
      return JsonResponse(response)
    return JsonResponse(response)

archive/templates/object/comment.html
{% load static %}
{% if ajax.editable and perms.archive.change_comment %}
<form>
{% csrf_token %}
{% endif %}
<div class="d-flex">
  <div class="flex-grow-1">
    <div class="d-flex py-1">
      <div class="col">
        {% if ajax.editable and perms.archive.change_comment %}
          {% if comment.user == user or user.is_staff %}
            <textarea class="form-control" name="content" data-autoresize>{{ comment.content }}</textarea>
          {% else %}
            <span class="text-muted">{% translate "you are not allowed to edit this comment"|capfirst %}</span><br>
          {% endif %}
        {% else %}
          <div class="comment">
            {% if show_thumbnail %}
              <div class="thumbnail">
                <a href="{% url 'archive:image' comment.image.slug %}"><img src="/documents/{{ comment.image.thumbnail }}" alt="{{ comment.image.title }}" title="{{ comment.image.title }} - {{ comment.image.description }}"></a>
              </div>
            {% endif %}
            <div class="content">
              <h4>{% if comment.user.first_name %}{{ comment.user.first_name }} {{ comment.user.last_name }}{% else %}{{ comment.user }}{% endif %} {% translate 'wrote on' %} {{ comment.date_created|date:'d/m/Y' }}{% if show_thumbnail %} {% translate 'on'%} <a href="{% url 'archive:image' comment.image.slug %}">{{ comment.image.title|title }}{% endif %}</a>:</h4>
              {{ comment.content|markdown|safe }}
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="ms-3 d-flex flex-column align-items-end justify-content-start flex-shrink-0">
    {% if user == comment.user or user.is_staff %}
      {% if ajax.editable %}
        <button 
          type="submit" 
          class="btn btn-outline-success"
          data-action
          data-method="post"
          data-url = "{% url 'cmnsd:dispatch_object_by_id_and_slug' 'comment' comment.id comment.token|default:comment.user.username %}"
          data-body="form"
          data-refresh-url="{% url 'cmnsd:dispatch_object_by_id_and_slug' 'comment' comment.id comment.token|default:comment.user.username %}"
          data-refresh-map='{"comment":"#comment-{{ comment.id }}"}'
          >
          <img src="{% static 'img/bootstrap-icons/floppy.svg' %}" alt="{% translate 'save comment' %}" title="{% translate 'save comment' %}" data-bs-toggle="tooltip" data-bs-placement="right" >
        </button>
        <button 
          type="button" 
          class="btn btn-outline-danger"
          data-action
          data-method="delete"
          data-url = "{% url 'cmnsd:dispatch_object_by_id_and_slug' 'comment' comment.id comment.token|default:comment.user.username %}"
          data-body='{"delete":"true"}'
          data-refresh-url="{% url 'cmnsd:dispatch_field_of_object_by_id_and_slug' 'image' comment.image.id comment.image.slug 'comments' %}"
          data-refresh-map='{"comments":"#comments"}'
          data-confirm="{% translate 'Are you sure you want to delete this comment?' %}"
          >
          <img src="{% static 'img/bootstrap-icons/trash.svg' %}" alt="{% translate 'delete comment' %}" title="{% translate 'delete comment' %}" data-bs-toggle="tooltip" data-bs-placement="right" >
        <button 
          type="button" 
          class="btn btn-outline-secondary"
          data-action
          data-url = "{% url 'cmnsd:dispatch_object_by_id_and_slug' 'comment' comment.id comment.token|default:comment.user.username %}"
          data-map='{"comment":"#comment-{{ comment.id }}"}'
          >
          <img src="{% static 'img/bootstrap-icons/x.svg' %}" alt="{% translate 'cancel edit comment' %}" title="{% translate 'cancel edit comment' %}" data-bs-toggle="tooltip" data-bs-placement="right" >
        </button>
      {% else %}
        <button 
          type="button" 
          class="btn btn-outline-secondary"
          data-action
          data-url = "{% url 'cmnsd:dispatch_object_by_id_and_slug' 'comment' comment.id comment.token|default:comment.user.username %}"
          data-body = '{"editable":"true"}'
          data-map='{"comment":"#comment-{{ comment.id }}"}'
          >
          <img src="{% static 'img/bootstrap-icons/pencil.svg' %}" alt="{% translate 'edit comment' %}" title="{% translate 'edit comment' %}" data-bs-toggle="tooltip" data-bs-placement="right" >
        </button>
      </div>
    {% endif %}
  {% endif %}
</div>
{% if ajax.editable and perms.archive.change_comment %}
</form>
{% endif %}

archive/templates/object/location.html
{% load static %}
{% if not location.sublocations.exists %}
  <div class="col-md-2">
    {% ifchanged location.country %}{{ location.country.name }}{% endifchanged %}
  </div>
  <div class="col-md-3">
    {% ifchanged location.region %}<a href="{% url 'archive:locations' %}?name={{ location.region.name }}">{{ location.region.name }}</a>{% endifchanged %}
  </div>
  <div class="col-md-6">
    <strong>{{ location.name }}</strong>
    <!-- Alternatives-->
    {% if location.alternatives.exists %}
      <div class="alternatives">
        {% for alternative in location.alternatives.all %}
          <em class="alternative">{{ alternative.name }}</em>{% if not forloop.last %},{% endif %}
        {% endfor %}
      </div>
    {% endif %}
    <!-- Description -->
    {% if location.description %}
      <div class="description">{{ location.description|safe }}</div>
    {% endif %}
    <!-- People -->
    {% if location.people|length > 0 %}
      <div class="people">
        {% for person in location.people %}
         {% include 'element/person_full_name.html' with person=person %}
         {% if location in person.birth.locations.all %}*{% elif location in person.death.locations.all %}&dagger;{% endif %}
         {% if not forloop.last %}<br>{% endif %}
        {% endfor %}
      </div>
    {% endif %}
    {% if ajax.editable %}
      <div class="edit location">
        <form
            data-action
            data-method="post"
            data-url="{% url 'cmnsd:dispatch_object_by_id_and_slug' 'location' location.id location.slug %}"
            data-map='{"location": "#location-{{ location.id }}"}'
            data-refresh-url="{% url 'cmnsd:dispatch' 'locations' %}"
            data-refresh-map='{"location": "#locations"}'
            >
          <div class="input-group input-group-sm">
            <span class="input-group-text">{% translate 'name' %}</span>
            <input type="text" class="form-control" name="name" value="{{ location.name }}" />
          </div>
          <div class="input-group input-group-sm">
            <span class="input-group-text">{% translate 'description' %}</span>
            <textarea class="form-control" name="description">{{ location.description }}</textarea>
          </div>
          <div class="input-group input-group-sm">
            <span class="input-group-text">{% translate 'parent location' %}:</span>
            {% if location.parent %}
              <span class="input-group-text">
                {{ location.parent }}
                <a data-action
                    data-method="post"
                    data-url="{% url 'cmnsd:dispatch_object_by_id_and_slug' 'location' location.id location.slug %}"
                    data-params='{"parent__id": "{{ location.parent.id }}"}'
                    data-map='{"location": "#location-{{ location.id }}"}'
                    data-refresh-url="{% url 'cmnsd:dispatch' 'locations' %}"
                    data-refresh-map='{"location": "#locations"}'
                    >
                  <img src="{% static 'img/bootstrap-icons/x.svg' %}" 
                       alt="{% translate 'remove parent location' %}" 
                       title="{% translate 'remove parent location' %}" 
                      />
                </a>
              </span>
            {% else %}
              <input type="text" class="form-control" name="parent" placeholder="{% translate 'start typing...' %}" 
                      data-autosuggest
                        data-url="{% url 'cmnsd:dispatch' 'locations' %}?format=json"
                        data-param="{{ search_query_character|default:'q' }}"
                        data-field-input="name"
                        data-field-hidden="slug"
                        data-field-prefix="parent__"
                        data-display-fields="name, description"
                        data-container="location"
                        data-allow-empty="1">
            {% endif %}
          </div>
          <button type="submit" class="btn btn-sm btn-primary">{% translate 'save' %}</button>
        </form>
      </div>
    {% endif %}
  </div>
  <div class="col-md-1 text-end">
    {% if perms.archive.change_location %}
      <a class="btn btn-sm btn-primary-outline">
        <img  src="{% if ajax.editable %}{% static 'img/bootstrap-icons/x.svg' %}{% else %}{% static 'img/bootstrap-icons/pencil.svg' %}{% endif %}" 
              alt="{% translate 'edit' %}" 
              title="{% translate 'edit' %}" 
              data-action
              data-url="{% url 'cmnsd:dispatch_object_by_id_and_slug' 'location' location.id location.slug %}"
              data-map='{"location": "#location-{{ location.id }}"}'
              {% if not ajax.editable %}data-params='{"editable": "true"}'{% endif %}
              />
      </a>
    {% endif %}
    </div>
{% endif %}