archive/urls.py
from django.urls import path

from . import views
# from cmnsdjango import views as cmnsviews
#from core.views import SignUpView

app_name = 'archive'
urlpatterns = [
  # Images
  path('', views.ImageListView.as_view(), name='home'),
  path('object/<int:pk>/', views.ImageRedirectView.as_view(), name='image-redirect'),
  # path('object/<int:pk>/comment/', views.AddCommentView.as_view(), name='comment'),
  path('object/<int:pk>/edit/', views.EditImageView.as_view(), name='image-edit'),
  path('object/new/', views.AddImageView.as_view(), name='add-image'),
  path('object/<str:slug>/', views.ImageView.as_view(), name='image'),
  # path('object/<str:slug>/love/', views.ToggleFavoriteImage.as_view(), name='love-image'),
  path('object/<int:pk>:<str:slug>/regeneratethumbnail/', views.RegenerateThumbnailView.as_view(), name='regenerate-thumbnail'),
  # Special Image views
  path('objects/<int:decade>/', views.ImageListView.as_view(), {'columns': ('decade')}, name='images-by-decade'),
  path('objects/by:<str:user>/', views.ImageListView.as_view(), {'columns': ('user')}, name='image-by-uploader'),
  path('objects/<str:tag>/', views.ImageListView.as_view(), {'columns': ('tag')}, name='image-with-tag'),
  path('objects/a/comments/', views.aListComments.as_view(), name='acomments'),
  path('objects/', views.ImageListView.as_view(), name='images'),

  # People
  path('people/', views.PersonListView.as_view(), name='people'),
  path('person/<int:pk>/', views.PersonRedirectView.as_view(), name='person-short'),
  path('person/<int:pk>/edit/', views.EditPersonView.as_view(), name='person-edit'),
  path('person/<int:pk>/<name>/', views.PersonView.as_view(), name='person'),
  path('person/new/', views.AddPersonView.as_view(), name='add-person'),
  path('person/add/', views.AddPerson.as_view(), name='new-add-person'),
  # Portrait
  # path('person/<int:subject>/portrait:<int:removed_image>/delete/', views.RemovePortraitView.as_view(), name='remove-portrait'),
  # Relationships
  path('person/<int:subject>/<str:type>:<int:removed_person>/delete/', views.PersonRemoveRelationView.as_view(), {'columns': ('up', 'relation', 'down')}, name='remove-relationship'),
  path('person/add-relation/', views.PersonAddRelationView.as_view(), name='add-relationship'),
  path('person/<int:pk>/<str:slug>/suggest-family/', views.SuggestFamilyView.as_view(), name='suggest-family'),
  # Tree
  path('tree/<int:pk>/', views.TreeView.as_view(), name="tree"),
  # Add Image
  path('person/<int:subject_id>:<str:subject_slug>/add-image/', views.AddImageView.as_view(), name='add-person-image'),
  
  # Tags 
  path('tags/', views.TagListView.as_view(), name='tags'),
  path('tag/new/', views.AddTagView.as_view(), name='add-tag'),
  path('tag/<str:slug>/', views.EditTagView.as_view(), name='edit-tag'),

  # Notes
  path('notes/', views.NotesListView.as_view(), name='notes'),
  path('note/<int:pk>/edit/', views.EditNoteView.as_view(), name='note-edit'),
  path('note/<int:pk>/', views.NoteView.as_view(), name='note'),
  path('note/<int:pk>/<title>/', views.NoteView.as_view(), name='note-with-name'),
  path('note/new/', views.AddNoteView.as_view(), name='add-note'),

  # Comments
  path('comments/', views.CommentListView.as_view(), name='comments'),
  
  # Attachments
  path('attachments/', views.AttachmentListView.as_view(), name='attachments'),
  path('attachment/new/', views.AttachmentAddView.as_view(), name='add-attachment'),
  path('attachments/<str:user>/', views.AttachmentListView.as_view(), name='user-attachments'),
  path('attachment/<str:slug>/delete/', views.AttachmentDeleteView.as_view(), name='delete-attachment'),
  path('attachment/<str:slug>/edit/', views.AttachmentEditView.as_view(), name='edit-attachment'),
  path('attachment/<str:slug>/create-image/', views.CreateImageFromAttachmentView.as_view(), name='create-image-from-attachment'),
  path('attachment/<str:slug>/', views.AttachmentStreamView.as_view(), name='attachment'),
  
  # Locations
  path('locations/', views.LocationListView.as_view(), name='locations'),
  
  # Accounts
  path('settings/', views.PreferencesView.as_view(), name='settings'),
  path("sign-up/", views.SignUpView.as_view(), name='signup'),

  # # JSON
  # # JSON GET Attributes
  # path('json/<str:model>/<int:pk>:<str:slug>/attribute/<str:field>/', cmnsviews.JsonGetAttributes.as_view(), name='json-get-attributes-by-pk-slug'),
  # path('json/<str:model>/<str:slug>/attribute/<str:field>/', cmnsviews.JsonGetAttributes.as_view(), name='json-get-attributes'),
  # path('json/<str:model>/attribute/<str:field>/', cmnsviews.JsonGetAttributes.as_view(), name='json-get-attributes-for-self'),
  # # JSON GET Suggestions
  # path('json/<str:model>/<int:pk>:<str:slug>/suggest/<str:field>/', cmnsviews.JsonGetSuggestions.as_view(), name='json-get-suggestions-by-pk-slug'),
  # path('json/<str:model>/<str:slug>/suggest/<str:field>/', cmnsviews.JsonGetSuggestions.as_view(), name='json-get-suggestions'),
  # path('json/<str:model>/suggest/<str:field>/', cmnsviews.JsonGetSuggestions.as_view(), name='json-get-suggestions-for-self'),
  # # JSON SET Attributes
  # path('json/<str:model>/<int:pk>:<str:slug>/set/<str:field>/', cmnsviews.JsonSetAttribute.as_view(), name='json-set-attribute-by-pk-slug'),
  # path('json/<str:model>/<str:slug>/set/<str:field>/', cmnsviews.JsonSetAttribute.as_view(), name='json-set-attribute'),
  # path('json/<str:model>/set/<str:field>/', cmnsviews.JsonSetAttribute.as_view(), name='json-set-attribute-for-self'),
  # # JSON getAttribute Form
  # path('json/<str:model>/<str:slug>/add/<str:field>/', cmnsviews.GetJsonAddObjectForm.as_view(), name='json-suggestion-form'),
  # # path('json/person:<int:pk>:<str:slug>/attribute/<str:attribute>/', views.JsonGetAttributeOfPerson.as_view(), name='json-get-attribute-of-person'),
  # path('json/object:<int:pk>:<str:slug>/comments/', views.aListComments.as_view(), name='acommentsforimage'),
  # path('json/object:<int:pk>:<str:slug>/commentform/', views.aFetchCommentForm.as_view(), name='fetchcommentform'),
  # path('json/object:<int:pk>:<str:slug>/postcomment/', views.aPostComment.as_view(), name='postcomment'),
  
]

family/urls.py
"""family URL Configuration"""

from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  # path('pick/', include('datepicker.urls')),
  path('', include('archive.urls')),
  path('ajax/', include('cmnsd.urls')),
  path('admin/', admin.site.urls),
  path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archive/models/BaseIcon.py
from django.db import models

class BaseIcon(models.Model):
  icon = models.CharField(max_length=255, blank=True, help_text='bootstrap icon name')

  class Meta:
    abstract = True

  def get_icon_file(self):
    if self.icon:
      return f'img/bootstrap-icons/{self.icon}.svg'
    return 'img/bootstrap-icons/list.svg'

archive/models/comment.py
from django.db import models
from .image import Image
from django.urls import reverse

from cmnsd.models.cmnsd_basemodel import BaseModel
  
class Comment(BaseModel):
  # Content
  content             = models.TextField(help_text='Markdown supported')
  image               = models.ForeignKey(Image, related_name='comments', on_delete=models.CASCADE)
  
  class Meta:
    ''' Unique together
        Any comment to an image should be unique for that image and user,
        disallowing double comments.
    '''
    unique_together = ('user', 'image', 'content')
    ordering = ['-date_created']

  def __str__(self):
    deleted = ' (deleted)' if self.status == 'x' else ''
    return self.user.username + ' on ' + self.image.title + deleted
  
  def get_absolute_url(self):
    return reverse('archive:image', kwargs={'slug': self.image.slug})

archive/models/image.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from PIL import Image as PIL
from pathlib import Path
from django.core.validators import MaxValueValidator, MinValueValidator
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _

from math import floor

from .tag import Tag
from .person import Person
from .Category import Category

from cmnsd.models.cmnsd_basemodel import BaseModel, VisibilityModel
from cmnsd.models.cmnsd_basemethod import ajax_function, searchable_function
from cmnsd.views.cmnsd_filter import FilterMixin
from cmnsd.views.utils__request import RequestMixin

# Create Thumbnail function
def get_thumbnail(image):
  # Check if suffix is supported.
  if image.name[-4:].lower() not in ['.jpg', '.png'] and \
     image.name[-5:].lower() not in ['.jpeg',]:
    # There is an image ready that reads Format Not Supported. This is a
    # friendly way to inform the user of the error.
    return 'documents/format_not_supported.jpg'
  #from PIL import Image
  import PIL
  PIL.Image.MAX_IMAGE_PIXELS = 933120000
  ''' Store Target Information '''
  tgt_width = 300
  tgt_path = settings.MEDIA_ROOT.joinpath('thumbnails/')
  tgt_file = str(image.name)
  ''' Check if thumbnails_dir exists '''
  if not tgt_path.exists():
    tgt_path.mkdir(parents=True, exist_ok=True)
  ''' Set destination '''
  try:
    with PIL.Image.open(image.path) as img:
      width, height = img.size
      ratio = width / height
      tgt_height = int(tgt_width / ratio)
      img = img.resize((tgt_width, tgt_height), PIL.Image.Resampling.LANCZOS)
      img.save(settings.MEDIA_ROOT.joinpath(tgt_file))
      return tgt_file
  except Exception as e:
    return None

class Group(BaseModel):
  title               = models.CharField(max_length=255, blank=True)
  description         = models.CharField(max_length=512, blank=True, null=True)
  user                = models.ForeignKey(User, on_delete=models.CASCADE)
  tag                 = models.ManyToManyField(Tag, blank=True, related_name='groups')
  
  def __str__(self):
    title = self.title
    ''' Prepend title with tag if there is one tag set. 
        If more tags are set, it would get too messy. 
    '''
    if self.tag and self.tag.all().count() == 1:
      for tag in self.tag.all():
        title = f"{ tag }: { title }"
    ''' Append title with short description if set 
    '''
    if self.description:
      title += ' (' + self.description[:32]
      if len(self.description) > 32:
        title += '...'
      self.title += ')'
    return title

  def count_images(self):
    return self.images.exclude(status='x').count()

class Attachment(BaseModel):
  slug                = models.CharField(max_length=255, unique=True)
  file                = models.FileField(null=True, upload_to='files', help_text='Possible to attach file to an image. Use for pdf, doc, excel, etc.')
  description         = models.CharField(max_length=512, blank=True, null=True)
  # Meta
  size                = models.IntegerField(default=0)
  is_deleted          = models.BooleanField(default=False)

  def __str__(self) -> str:
    description = str(self.description)
    if len(description) < 1:
      description = self.slug
    # if self.is_deleted:
    #   description = f"[Deleted] { description }"
    return str(description)
    
  def get_absolute_url(self):
      return reverse("archive:attachment", kwargs={"slug": self.slug})
  
  def filename(self):
    return Path(str(self.file)).name
  
  def extension(self):
    return Path(str(self.file)).suffix[1:].lower()

  def storeSize(self):
    from os import stat
    file_stats = stat(settings.MEDIA_ROOT.joinpath(str(self.file  )))
    self.size = file_stats.st_size
    self.save()

  ''' Display Image File size. Calculate if not stored yet '''
  def getSize(self):
    ''' https://stackoverflow.com/questions/5194057/better-way-to-convert-file-sizes-in-python '''
    from math import floor, pow, log
    if self.size == 0:
      self.storeSize()
    if self.size == 0:
      return "0B"
    size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
    i = int(floor(log(self.size, 1024)))
    p = pow(1024, i)
    s = round(self.size / p, 2)
    return "%s %s" % (s, size_name[i])

''' Use default random value when migrating to slug '''
import random
def random_string():
  return str(random.randint(10000, 99999))

class Image(BaseModel, RequestMixin, FilterMixin):
  # Document details
  slug                = models.CharField(max_length=255, unique=True, default=random_string)
  source              = models.FileField()
  thumbnail           = models.CharField(max_length=2000, blank=True, null=True)
  title               = models.CharField(max_length=255)
  description         = models.TextField(blank=True, help_text='Markdown supported')
  document_source     = models.CharField(max_length=255, blank=True, help_text='Link or textual description of source')
  # Relations
  category            = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, related_name='images')
  people              = models.ManyToManyField(Person, blank=True, related_name='images', help_text='Tag people that are on the photo')
  tag                 = models.ManyToManyField(Tag, blank=True, related_name='images')
  attachments         = models.ManyToManyField(Attachment, blank=True, related_name='images')
  is_portrait_of      = models.OneToOneField(Person, on_delete=models.CASCADE, related_name='portrait', blank=True, null=True)
  portrait_of         = models.ManyToManyField(Person, blank=True, related_name='portraits', help_text='Tag people for whom this image is a portrait')
  in_group            = models.ManyToManyField(Group, blank=True, related_name='images', help_text='Group images')
  family              = models.CharField(max_length=64, null=True, blank=True, help_text=_('Add image to family collection if no family member can be tagged'))
  # Dating
  MONTHS = [(1, _('january')), (2, _('february')), (3, _('march')), (4, _('april')), (5, _('may')), (6, _('june')), (7, _('july')), (8, _('august')), (9, _('september')), (10, _('october')), (11, _('november')), (12, _('december'))]
  year                = models.PositiveSmallIntegerField(blank=True, null=True, help_text='')
  month               = models.PositiveSmallIntegerField(blank=True, null=True, help_text='', choices=MONTHS)
  day                 = models.PositiveSmallIntegerField(blank=True, null=True, help_text='', validators=[MaxValueValidator(31), MinValueValidator(1)])
  # Meta
  size                = models.IntegerField(default=0)
  width               = models.IntegerField(default=0)
  height              = models.IntegerField(default=0)
  
  visibility_frontpage     = models.BooleanField(default=True)
  visibility_person_page   = models.BooleanField(default=True)
  
  def date(self):
    """ Returns the date of the image by combining the year, month and day fields """
    return f"{self.day} {self.MONTHS[self.month-1][1]} {self.year}"
  
  def __str__(self):
    return self.get_indexed_name()

  ''' Shorthand Ajax Functions to access multiple fields '''
  @ajax_function
  def origin(self):
    return {
      'document_source': str(self.document_source),
      'date': f"{ self.day if self.day else '*'}-{self.month if self.month else '*'}-{self.year if self.year else '*'}",
      'day': self.day,
      'month': self.month,
      'year': self.year,
      'months': self.MONTHS,
    }
  @ajax_function
  def metadata(self):
    return {
      'attachments': self.get_attachments(),
      'size': self.getSize(),
      'dimensions': {
        'width': self.width,
        'height': self.height,
      },
      'extension': self.extension(),
      'user': self.user,
      'users': User.objects.all(),
      'date_shared': self.date_created,
    }
  @ajax_function
  def classification(self):
    return {
      'tag': self.tag.all(),
      'groups': self.in_group.all(),
      'grouped_items': self.grouped_items(),
      'family': self.family,
      'family_collection': self.family_collection(),
      'automated_family': self.automated_family(),
      'available_families': self.families(),
    }
  
  @ajax_function
  def actionlist(self):
    return True
  
  @searchable_function
  def familycollection(self):
    return self.family_collection()
  
  @searchable_function
  def decade(self):
    if self.year:
      decade = floor(self.year / 10) * 10
      return decade
    return None
  
  ''' Get Save Slug
      Loop through existing slugs and append slug with counter if Unique contraint would fail
  '''
  def get_safe_slug(self, title, is_deleted):
    slug = slugify(title).lower()
    if is_deleted:
      slug = f"[deleted]_{slug}"
    images = Image.objects.all().values_list('slug')
    if images.filter(slug=slug).count() > 0:
      i = 1
      while images.filter(slug=f"{slug}{str(i)}").count() > 0:
        i += 1
      slug = f"{slug}{str(i)}"
    return slug

  def get_indexed_name(self):
    title = self.title if self.title != '' else '--no title--'
    id = str(self.id)
    while len(id) < 4:
      id = '0' + id
    if self.status == 'x':
      title += ' (deleted)'
    return id + ' ' + title
  
  ''' Related Object Methods'''
  def count_comments(self):
    return self.get_comments().count()
  def get_comments(self):
    return self.filter(self.comments)
  def count_attachments(self):
    return self.get_attachments().count()
  def get_attachments(self):
    return self.filter(self.attachments)
  
  def get_groups(self):
    groups = {}
    for group in self.in_group.all():
      if group.images.exclude(status='x').count() > 1:
        groups[group.title] = group.images.exclude(status='x').count()
    return groups
  def get_grouped_images(self):
    groups = {}
    for group in self.in_group.all():

archive/templates/archive/snippets/error_no_objects.html
{% load i18n %}
<div class="alert alert-danger" role="alert">
  {% translate 'An error occurred' %}:
  {% blocktranslate %}There are no {{ object_type }} to show.{% endblocktranslate %}<br>
</div>

archive/templates/archive/snippets/filter_image_by_category.html
{% if categories|length > 1 %}- 
  {% translate 'filter by'|capfirst %} {% translate 'category' %}: 
  {% for category in categories %}
    {% if category %}
      {% if category == current_category %}
        {{ category|default:''|title }}
      {% else %}
        <a href="{% url 'archive:images' %}?{% include '../snippets/fixparams.html' with ignore='category' %}category={{ category }}"{% if category == current_category %} disabled{% endif %}>{{ category|title }}</a>
      {% endif %}
      {% if not forloop.last %} | {% endif %}
    {% endif %}
  {% endfor %}
{% endif %}

archive/templates/archive/snippets/filter_image_by_family.html
{% load i18n %}{% if families|length > 1 %}
  {% translate 'filter by'|capfirst %}: 
  {% for family in families %}
    {% if family == current_family %}
      {{ family|title }}
    {% else %}
      <a href="{% url 'archive:images' %}?{% include '../snippets/fixparams.html' with ignore='family' %}family={{ family }}"{% if family == current_family %} disabled{% endif %}>{{ family|title }}</a>
    {% endif %}
    {% if not forloop.last %} | {% endif %}
  {% endfor %}
{% endif %}

archive/templates/archive/snippets/image.html
{% load i18n %}{% load static %}{% if not object.is_deleted %}
  <div class="object{% if not object.visibility_frontpage or not object.visibility_person_page %} hidden{% endif %}" id="{{ object.title|slugify }}">
    <h2><span class="object-id">#{{ object.id }}</span><a href="{% url 'archive:image' object.slug %}" title="{{ object.title }}" tabindex="{{ forloop.counter }}">{{ object.title|truncatewords_html:3 }}</a></h2>
    <div class="column left">
      <a href="{% url 'archive:image' object.slug %}" title="{{ object.title }}">
        {% if object.thumbnail %}
          <img src="/documents/{{ object.thumbnail }}" alt="{{ object.title }}" title="{{ object.title }} - {{ object.description }}">
        {% else %}
          <svg class="bi" width="150" height="100" fill="#333"><use xlink:href="{% static 'bootstrap-icons/bootstrap-icons.svg' %}#image-fill"></svg>
        {% endif %}
      </a>
    </div>
    <div class="column right">
      {{ object.description|markdown|safe|truncatewords_html:10 }}
      <!-- Object Meta data -->
      <ul class="metadata no-bullets">
        <!-- Category -->
        {% if object.category %}
          <li class="bi">
            <img src="{% static object.category.get_icon_file %}" alt="{% translate 'category' %}" title="{% translate 'category of this photo'|capfirst %}" data-bs-toggle="tooltip" data-bs-placement="left"> 
            {% if object.category.parent %}<a href="{% url 'archive:images' %}?category={{ object.category.parent.slug }}" class="tag" title="{{ object.category.parent.images.all.count }} images with category '{{ object.category.parent.name|title }}'" data-bs-toggle="tooltip" data-bs-placement="top">{% translate object.category.parent.name %}</a>: {% endif %}
            <a href="{% url 'archive:images' %}?category={{ object.category.slug }}" class="tag" title="{{ object.category.images.all.count }} images with category '{{ object.category.name|title }}'" data-bs-toggle="tooltip" data-bs-placement="top">{{ object.category.name }}</a> {% if object.category.images.all.count > 0 %}({{ object.category.images.all.count }}){% endif %}
          </li>
        {% endif %}
        <!-- Date-->
        {% if object.day or object.month or object.year %}
          <li class="date bi bi-calendar-event-fill" data-bs-toggle="tooltip" data-bs-placement="right" title="{% translate 'date of origin of object'|capfirst %}.">
            {% if object.day %}{{ object.day }}-{% if not object.month %}?-{% endif %}{% endif %}{% if object.month %}{{ object.month }}-{% if not object.year %}?{% endif %}{% endif %}{% if object.year %}<a href="{% url 'archive:images-by-decade' object.year %}" title="Bekijk alles uit {{ object.year }}">{{ object.year }}</a>{% endif %}</li>
        {% endif %}
        <!-- Image is hidden -->
        {% if not object.visibility_frontpage %}<li class="bi bi-info-circle-fill"> {% translate 'hidden'|capfirst %}</li>{% endif %}
        <!-- Love image? -->
        {% if object in user.preference.favorites.all %}<li class="bi bi-heart-fill"> {% translate 'you love this image'|capfirst %}</li>{% endif %}
        <!-- People -->
        {% if perms.archive.view_person and object.people.all.count > 0 and object.people.all.count < 6 %}
          {% for person in object.people.all %}
            <li class="bi bi-person-fill"> <a href="{% url 'archive:person' person.id person.name %}" data-bs-toggle="tooltip" title="{% translate 'see information of'|capfirst %} {{ person.full_name }}">{{ person.name }}</a></li>
          {% endfor %}
        {% elif perms.archive.view_person and object.people.all.count > 6 %}
          {% for person in object.people.all %}
            {% if forloop.counter < 4 %}
              <li class="bi bi-person-fill"> <a href="{% url 'archive:person' person.id person.name %}" title="Bekijk gegevens van {{ person.full_name }}">{{ person.name }}</a></li>
            {% elif forloop.counter == 4 %}
              <li class="bi bi-people-fill"> ... en {{ forloop.revcounter }} meer</li>
            {% endif %}
          {% endfor %}
        {% endif %}
        <!-- Family Collection -->
        {% if object.family_collection|length > 0 %}
          <li class=" bi bi-collection" data-bs-toggle="tooltip" data-bs-placement="right" title="{% translate 'this image is part of a family collection'|capfirst %}."> {% for family in object.family_collection %}<a href="{% url 'archive:images' %}?family={{ family }}" title="{% translate 'Open family collection of' %} {{ family }}">{{ family }}</a>{% if not forloop.last %}, {% endif %}{% endfor %} </li>
        {% endif %}
        <!-- Tags -->
        {% if perms.archive.view_tag and object.tag.all.count > 0 %}
          {% if object.tag.all.count > 5 %}
            {% for tag in object.tag.all %}
              {% if forloop.counter < 6 %}
                {% include 'archive/snippets/tag.html' with compact=True %}
              {% elif forloop.counter == 6 %}
                <li class="bi bi-tag"> ... {{ forloop.revcounter }} meer</li>
              {% endif %}
            {% endfor %}
          {% else %}
            {% for tag in object.tag.all %}
              {% include 'archive/snippets/tag.html' with compact=True %}
            {% endfor %}
          {% endif %}
        {% endif %}
        <!-- Grouping -->
        {% if object.in_group.all.count > 0 %}
              {% for group in object.in_group.all %}
                <li class="bi bi-collection-fill"> {{ group.title }} ({{ group.images.all.count}})</li>
              {% endfor %}
            {% endif %}
        <!-- Comments -->
        {% if perms.archive.view_comment and object.count_comments > 0 %}
          <li class="comments bi bi-chat-right-fill"> <a href="{% url 'archive:image' object.slug|default:'needs-a-title' %}#comments" title="{{ object.title }}">{{ object.count_comments }} reactie{{ object.count_comments|pluralize:'s' }}</a></li>  
        {% endif %}
        <!-- Attachments -->
        {% if perms.archive.view_attachment and object.count_attachments > 0 %}
          <li class="attachments bi-paperclip"> {{object.attachments.all.count }} bijlage{% if object.attachments.all.count > 1 %}n{% endif%}</li>
        {% endif %}
      </ul>
    </div>
  </div>
{% endif %}

archive/templates/archive/snippets/person_link.html
<span class="name">
  {% if not person.private %}<a href="{% url 'archive:person' person.id person.slug|default:'details' %}" data-bs-toggle="tooltip" data-bs-placement="top" title="Bekijk details van {{ person.full_name }}">{% endif %}{{ person.full_name }}{% if not person.private %}</a>{% endif %}</span>
<span class="date">
  {{ person.birth.year|default:'&nbsp;&nbsp;&nbsp;*'}} - {{ person.death.year|default:'&dagger;' }}
  {% comment %} {% if person.birth %}{{ person.birth.year }}{% elif person.death %}&nbsp;&nbsp;&nbsp;&nbsp;{% endif %}{% if person.death or person.moment_of_death_unconfirmed %} - {% if person.death %}{{ person.death.year }}{% else %}&dagger;{% endif %}{% endif %} {% endcomment %}
</span>
{% if not suppress_icons %}
  <span class="icons">
    <!-- bio -->{% if person.bio %}<i class="bi bi-journal-text" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ person.name }} heeft een biografie"></i>{% endif %}
    <!-- images -->{% if person.images.all.count > 0 %} <i class="bi bi-image{% if person.images.all.count > 1 %}s{% endif %}" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ person.images.all.count }} afbeeldingen met {{ person.name }}"></i>{{ person.images.all.count }}{% endif %}
    <!-- notes -->{% if person.notes.all.count > 0 %} <i class="bi-stick{% if person.notes.all.count > 1 %}ies{% else %}y{% endif %}" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ person.notes.all.count }} notities met {{ person.name }}"></i>{{ person.notes.all.count }}{% endif %}
    <!-- comments -->{% if person.related_user.comments.all.count > 0 %} <a href="{% url 'archive:comments' %}?user={{ person.related_user.username }}" class="bi bi-chat" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ person.related_user.comments.all.count }} reacties door {{ person.name }}">{{ person.related_user.comments.all.count }}</a>{% endif %}
  </span>
{% endif %}

archive/templates/archive/snippets/tag.html
<li class="tag bi bi-tag-fill">
  <a href="{% url 'archive:image-with-tag' tag.slug %}" class="tag" title="{{ tag.images.all.count }} afbeeldingen met tag '{{ tag.title|title }}'" data-bs-toggle="tooltip" data-bs-placement="top">{% if compact %}{{ tag.name|title|truncatechars:12 }}{% else %}{{ tag.name|title }}{% endif %}</a> {% if tag.images.all.count > 0 %}({{ tag.images.all.count }}){% endif %}
</li>